-- Schema for user's bookshelf with basic CRUD

-- 1) Table
create table if not exists public.bookshelf (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  ol_key text not null,
  title text not null,
  author text,
  cover_i int,
  year int,
  status text not null default 'want-to-read' check (status in ('want-to-read','reading','read')),
  created_at timestamptz not null default now()
);

-- Prevent duplicates per user/book
create unique index if not exists bookshelf_user_book_unique on public.bookshelf(user_id, ol_key);

-- 2) RLS
alter table public.bookshelf enable row level security;

create policy if not exists "select own bookshelf"
  on public.bookshelf for select
  using (auth.uid() = user_id);

create policy if not exists "insert own bookshelf"
  on public.bookshelf for insert
  with check (auth.uid() = user_id);

create policy if not exists "update own bookshelf"
  on public.bookshelf for update
  using (auth.uid() = user_id);

create policy if not exists "delete own bookshelf"
  on public.bookshelf for delete
  using (auth.uid() = user_id);

